inherit_gem:
  switchcop: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'tmp/**/*'
    - '**/*/bundle'

Naming/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude: ["avo-api.gemspec"]

Metrics/MethodLength:
  Max: 17

Metrics/AbcSize:
  Max: 25

RSpec/ExampleLength:
  Max: 10

RSpec/AnyInstance:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: [ 'describe', 'context' ]
